Shop.WebApp/Controllers/SearchController.cs
using Microsoft.AspNetCore.Mvc;
using Shop.Data.Interfaces;
using Shop.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Shop.Controllers
{
    public class SearchController : Controller
    {

        private ISearch _merchRep;

        public SearchController(ISearch merchRep)
        {
            _merchRep = merchRep;
        }

        [HttpPost]
        public ViewResult Index(string search)
        {
                var searchMerches = new SearchFiltersViewModel
                {
                    searchMerches = _merchRep.GetSearchMerches.Where(x => x.Name.Contains(search))
                };

            return View(searchMerches);
        }
    }
}

Shop.WebApp/Controllers/ShoppingCartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Shop.Data.Interfaces;
using Shop.Data.Models;
using Shop.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Shop.Controllers
{
    public class ShoppingCartController: Controller
    {
        private IAllMerches _merchRep;
        private IShoppingCartItem _shp;
        private readonly ShoppingCart _shoppingCart;


        public ShoppingCartController(IAllMerches merchRep, ShoppingCart shoppingCart, IShoppingCartItem shp)
        {
            _merchRep = merchRep;
            _shoppingCart = shoppingCart;
            _shp = shp;
        }

        public ViewResult Index()
        {   
            
            var Items = _shoppingCart.getShopItems();
            _shoppingCart.listShopItems = Items;

            var obj = new ShoppingCartViewModel
            {
                shoppingCart = _shoppingCart
            };

            return View(obj);
        }
        
        [Authorize]
        public RedirectToActionResult addToCart(int id, string size)
        {
            var item = _merchRep.Merches.FirstOrDefault(i => i.Id == id);
            if (item != null)
            {
                _shoppingCart.AddToCart(item,size);
            }
            return RedirectToAction("Index");
        }


        public RedirectToActionResult delToCart(int id)
        {
            var item = _shp.ShoppingCartItemes.FirstOrDefault(i => i.Id == id);
            if (item != null)
            {
                _shoppingCart.DelToCart(item);
            }
            return RedirectToAction("Index");
        }

        public int Sum(string shoppingCartId)
        {
            var sum = _shp.ShoppingCartItemes.Where(i => i.ShoppingCartId == shoppingCartId).Sum(i=>i.Price);
                return sum;
        }


    }
}

Shop.WebApp/Views/Shared/AllMerches.cshtml
@model Shop.Data.Models.Merch

<div class=" col-lg-3">
    <div><img class="img-thumbnail" src="@Model.Img" alt="@Model.Name" /></div>
    
    </div>
<div class="col-lg-3">
    <h2>@Model.Name </h2>
    <p>Цена: @Model.Price.ToString("c")</p>
    <p style="display: inline-flex"><a href="/Item/@Model.url">Подробнее</a></p>
    <form name="qwe" asp-controller="ShoppingCart" asp-action="AddToCart" asp-route-id="@Model.Id" asp-route-size="size">
        <input type="radio" name="size" value="L"> L<Br>
        <input type="radio" name="size" value="M" checked> M<Br>
        <input type="radio" name="size" value="X"> X<Br>
        <input type="radio" name="size" value="XL"> XL<Br>
        <input type="submit" value="Добавить в корзину" class="btn btn-warning btn_color_more" style="margin-top: 1rem"/>
    </form>
</div>

Shop.WebApp/Views/Shared/OneItem.cshtml
@model Shop.Data.Models.Merch
    <div class=" col-lg-8" style="display:flex">
        <div><img class="img-thumbnail" src="@Model.Img" alt="@Model.Name" /></div>
        <div class="col-lg-4">
            <h2>@Model.Name </h2>
            <p>@Model.Description</p>
            <p>Цена: @Model.Price.ToString("c")</p>
            <form asp-controller="ShoppingCart" asp-action="AddToCart" asp-route-id="@Model.Id" asp-route-size="size">
                <select name="size" id="size">
                    <option value="L">L</option>
                    <option value="M" selected>M</option>
                    <option value="X">X</option>
                    <option value="XL">XL</option>
                </select>
                <input type="submit" value="Добавить в корзину" class="btn btn-warning btn_color_more" />
            </form>
        </div>
    </div>

Shop.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>@ViewBag.Title</title>
    <link rel=" stylesheet" href="~/css/bootstrap.min.css" type="text/css" />
    <link rel=" stylesheet" href="~/css/style_home.css" type="text/css" />

</head>
<body>
    <div class="container-fluid header" style="background-color:lightgray">
        <div class="row">
            <div class="col-sm-12 col-lg-3">
                <h1 asp-action="Index" asp-controller="Home">BIG HOUSE</h1>
                <span style="display:grid; font-size: 15px; padding-bottom: 1rem;">Официальный онлайн магазин BIG HOUSE</span>
                
            </div>
            <div class="col-sm-12 col-lg-9" style="font-size:1.5rem">
                
                    
                    
                        
                            <nav class="navbar navbar-expand-lg navbar-light mob_nav">
                                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation" style="position: absolute; right: 0; top: -70px;">
                                    <span class="navbar-toggler-icon"></span>
                                </button>
                                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                                    <div class="navbar-nav">
                                        <a class="nav-item nav-link active" href="/">Главная<span class="sr-only">(current)</span></a>
                                        <a class="nav-item nav-link" href="/Merches/List/t-shirts">Футболки</a>
                                        <a class="nav-item nav-link" href="/Merches/List/sweatshirts">Толстовки</a>
                                        <a class="nav-item nav-link" href="/Merches/List/caps">Кепки</a>
                                        <a class="nav-item nav-link" href="/Merches/List/bracelets">Браслеты</a>
                                        <div class="input-group mb-3" style="display:block">
                                            <form name="search" method="post" asp-controller="Search" asp-action="Index" asp-route-Name="search">
                                                <input required name="search" type="text" id="search" class="form-control" placeholder="Поиск" aria-label="Recipient's username" aria-describedby="button-addon2" style="border: 0; border-radius: 40px; margin-top: 8px;">
                                                <button type="submit" name="button" style="background-color: transparent; border: 0; position: absolute; right: 7px; top: 0px; line-height: 1; height: calc(1.5em + .75rem + 2px); z-index: 3;"><img src="~/img/search.svg" style="width:20px" /></button>
                                            </form>
                                            <div class="input-group-append">
                                            </div>
                                        </div>
                                        @if (User.Identity.IsAuthenticated == true)
                                        {
                                    <form method="post" asp-controller="Account" asp-action="Logout">
                                        <a class="nav-item nav-link" href="/ShoppingCart/">Корзина</a>
                                        <input type="submit" name="button" value="Выйти" style="background-color: transparent; border: none;">
                                    </form>
                                        }
                                    </div>
                                </div>
                            </nav>
                        
                    
                
            </div>
        </div>
    </div>
    @RenderBody()
</body>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="~/js/popUp.js"></script>
</html>